name: Deploy docs

on:
  release:
    types: [published]

permissions: {}

jobs:
  deploy:
    if: github.actor == 'juleshry'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: curl -s -X POST ${{ secrets.NETLIFY_BUILD_HOOK }}